### ISSUE TITLE
Broken responsive

### ISSUE THREAD

**Issue by ignazas** [simonasg1993/ca-dice-game#1]
![paveikslas](https://user-images.githubusercontent.com/7562987/32179191-6b85bf16-bd97-11e7-9176-12e0a1d08f73.png)
was ist das?
![paveikslas](https://user-images.githubusercontent.com/7562987/32179211-81a68ef6-bd97-11e7-82ea-fcc7d5999b28.png)

**Comment by simonasg1993** [comment]
fixed
