### ISSUE TITLE
Nepatikima iš Cookies skaityt vartotojo vardą

### ISSUE THREAD

**Issue by ignazas** [simonasg1993/ca-dice-game#2]
```
        if (isset($_COOKIE["sausainis_username"])) {
            echo '<div class="col font-italic justify-content-center d-flex align-items-center"><h3> Logged in as  ' . $_COOKIE["sausainis_username"] . '</h3></div>';
```
Cookie gali būti perrašytas kitos sistemos ar paties vartotojo.
Patikimiau ir saugiau duomenis imti iš sesijos.
Be to cookie vardui yra sveika naudoti unikalų prefixa, kad jis nesimašytų su kitom sistemom (pvz **$_COOKIE["dice-game_com_username"]** )

**Comment by simonasg1993** [comment]
fixed
